CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  wa_id VARCHAR(32) UNIQUE NOT NULL,
  display_name VARCHAR(128),
  role VARCHAR(32) NOT NULL DEFAULT 'user',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);